### ISSUE TITLE
qqbot.py运行时，出现报错

### ISSUE THREAD

**Issue by uefi233** [LUMOXu/Spit_chatBot#33]
运行日志如下
`当前进程pid: 2268

#################################################################
██████╗ ██╗   ██╗ ██████╗ ██████╗ ██████╗  ██████╗ ████████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██╔═══██╗██╔══██╗██╔═══██╗╚══██╔══╝
██████╔╝ ╚████╔╝ ██║     ██║   ██║██████╔╝██║   ██║   ██║
██╔═══╝   ╚██╔╝  ██║     ██║▄▄ ██║██╔══██╗██║   ██║   ██║
██║        ██║   ╚██████╗╚██████╔╝██████╔╝╚██████╔╝   ██║
╚═╝        ╚═╝    ╚═════╝ ╚══▀▀═╝ ╚═════╝  ╚═════╝    ╚═╝
                                            v0.5.1.1  BY FengLiu
#################################################################

[2023-07-12 18:52:56,531][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 Protocol -> device lock is disable. http api may fail.
[2023-07-12 18:53:12,036][MainThread/INFO] PyCqBot: 正在连接 go-cqhttp websocket 服务
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\client.py", line 139, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\http.py", line 130, in read_response
    raise ValueError(f"unsupported HTTP version: {d(version)}")
ValueError: unsupported HTTP version: HTTP/1.0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Spit_chatBot\qqbot.py", line 447, in <module>
    bot.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pycqBot\cqHttpApi.py", line 361, in start
    self._websocket_start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pycqBot\cqHttpApi.py", line 401, in _websocket_start
    asyncio.run(main_logic())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pycqBot\cqHttpApi.py", line 375, in main_logic
    async with websockets.connect(self.__host) as websocket:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\client.py", line 637, in __aenter__
    return await self
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\client.py", line 323, in handshake
    status_code, response_headers = await self.read_http_response()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\websockets\legacy\client.py", line 145, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response
PS D:\Spit_chatBot> Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.
Failed to write to log, write /dev/stdout: The pipe is being closed.`

**Comment by uefi233** [comment]
已解决，但重新运行时出现了如下错误:
File "D:\Spit_chatBot\qqbot.py", line 431, in <module>
    load_bot_config()
  File "D:\Spit_chatBot\qqbot.py", line 342, in load_bot_config
    configs = json.load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 17 column 18 (char 381)

**Comment by UEFI233** [comment]
已解决，但重新运行时出现了如下错误:
File "D:\Spit_chatBot\qqbot.py", line 431, in <module>
    load_bot_config()
  File "D:\Spit_chatBot\qqbot.py", line 342, in load_bot_config
    configs = json.load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 17 column 18 (char 381)

**Comment by sodalye** [comment]
请问后续错误是如何解决的

**Comment by uefi233** [comment]
> 请问后续错误是如何解决的
配置写错了导致的

**Comment by sodalye** [comment]
> > 请问后续错误是如何解决的
> > 配置写错了导致的

那看来我也写错了（笑着捂脸）
