### ISSUE TITLE
使用的问题。

### ISSUE THREAD

**Issue by mlpxt** [LUMOXu/Spit_chatBot#7]
我在安装的过程中，使用的是神灯VPN，但是这个VPN我只知道ip，不知道端口，代理服务器的话我只知道ip，不知道端口。这样的话，配置文件该怎么写。

**Comment by MoMorkIsGay** [comment]
win10及以上的话 打开设置搜索代理 代理服务器编辑就那里可以找到ip和端口

**Comment by mlpxt** [comment]
而且，在使用.\qqbot.py后他直接闪退，这个是因为里面的东西没有配置好吗？但是我在使用python然后一行一行复制粘贴后进行最后一句bot.start()后，他是正常的，可以登陆qq。也可以收到我另一个账号的信息。

**Comment by LUMOXu** [comment]
关于代理的问题，这个程序的原版只支持设置代理地址。

**Comment by LUMOXu** [comment]
闪退的原因不清楚，建议用ide运行看看报错，可能是程序utf-8与gbk的编码问题。

**Comment by mlpxt** [comment]
代理地址的话这个该怎么获取，需要购买吗还是说怎么做。

**Comment by LUMOXu** [comment]
跟你自己的vpn有关系，建议咨询他们

**Comment by MoMorkIsGay** [comment]
> ![图片](https://user-images.githubusercontent.com/108312263/237608326-f5013ae6-dcfd-4947-a4c3-74f742aafe3f.png) 我这边并没有看到ip和端口，请问该怎么找到

我使用的是clash，设置这里的代理服务器是开启的，很轻松找到

**Comment by mlpxt** [comment]
![图片](https://github.com/LUMOXu/Spit_chatBot/assets/108312263/cfd359d9-9058-4552-bc36-05061cb320de)
我重新安装了一个VPN，现在获取到了代理网址和ip，但是在使用的时候出现了这个情况，请问这个该怎么解决

**Comment by mlpxt** [comment]
这次倒是没有闪退，但是在我只发了一次1后他的内容却出现了两个1
![图片](https://github.com/LUMOXu/Spit_chatBot/assets/108312263/4e7b195c-dbd9-45f9-88cb-9db90ee96663)
而且在群里没有回复

**Comment by LUMOXu** [comment]
哦，消息重复这是个小bug，继续发看看有没有回复

**Comment by mlpxt** [comment]
在开始运行的时候他发出了这个
![图片](https://github.com/LUMOXu/Spit_chatBot/assets/108312263/d53cbbed-0036-4ddc-8380-de635e666980)
这是因为ChatGPT没有连接成功吗

**Comment by mlpxt** [comment]
![图片](https://github.com/LUMOXu/Spit_chatBot/assets/108312263/1f52b608-8ea1-49c2-ac91-99d5df92b19f)

不行啊，他还是不说话。请问怎么查看他是否正确连接到了ChatGPT

**Comment by LUMOXu** [comment]
奇怪。。。他根本没调用qqbot里的reply_msg函数，目前只有你有这个问题，重启一下试试？

**Comment by mlpxt** [comment]
我重新下载一下你的包在部署一遍吧。希望可以成功

**Comment by mlpxt** [comment]
请问assistant_config.json和bot_config.json这两个文件可以写成完全一样的吗

**Comment by LUMOXu** [comment]
可以，但注意里面的bot_group_info里的群号不能相同。

**Comment by mlpxt** [comment]
Ready to answer...
Internet issues! Will not answer this time.
[2023-05-11 20:12:13,179][MainThread/ERROR] PyCqBot: [Errno 2] No such file or directory: 'sticker.json'
Traceback (most recent call last):
  File "E:\conda\envs\qqbot\lib\site-packages\urllib3\util\url.py", line 440, in parse_url
    host = _normalize_host(host, scheme)
  File "E:\conda\envs\qqbot\lib\site-packages\urllib3\util\url.py", line 326, in _normalize_host
    b".".join([_idna_encode(label) for label in host.split(".")]),
  File "E:\conda\envs\qqbot\lib\site-packages\urllib3\util\url.py", line 326, in <listcomp>
    b".".join([_idna_encode(label) for label in host.split(".")]),
  File "E:\conda\envs\qqbot\lib\site-packages\urllib3\util\url.py", line 344, in _idna_encode
    raise LocationParseError(
urllib3.exceptions.LocationParseError: Failed to parse: Name '1：6987' is not a valid IDNA label

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\conda\envs\qqbot\lib\site-packages\requests\adapters.py", line 454, in send
    conn = self.get_connection(request.url, proxies)
  File "E:\conda\envs\qqbot\lib\site-packages\requests\adapters.py", line 343, in get_connection
    proxy = prepend_scheme_if_needed(proxy, "http")
  File "E:\conda\envs\qqbot\lib\site-packages\requests\utils.py", line 993, in prepend_scheme_if_needed
    parsed = parse_url(url)
  File "E:\conda\envs\qqbot\lib\site-packages\urllib3\util\url.py", line 451, in parse_url
    raise LocationParseError(source_url) from e
urllib3.exceptions.LocationParseError: Failed to parse: http://127.0.0.1：6987

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\conda\envs\qqbot\lib\site-packages\openai\api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "E:\conda\envs\qqbot\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\conda\envs\qqbot\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\conda\envs\qqbot\lib\site-packages\requests\adapters.py", line 456, in send
    raise InvalidURL(e, request=request)
requests.exceptions.InvalidURL: Failed to parse: http://127.0.0.1：6987

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Desktop\1\qqbot.py", line 200, in reply_msg
    replies = chat.parse_reply(chat.answer(temp_chat_record, prompt))  # may stuck at this step.
  File "C:\Users\admin\Desktop\1\chat.py", line 55, in answer
    response = openai.ChatCompletion.create(
  File "E:\conda\envs\qqbot\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "E:\conda\envs\qqbot\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "E:\conda\envs\qqbot\lib\site-packages\openai\api_requestor.py", line 216, in request
    result = self.request_raw(
  File "E:\conda\envs\qqbot\lib\site-packages\openai\api_requestor.py", line 528, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: Failed to parse: http://127.0.0.1：6987

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\conda\envs\qqbot\lib\site-packages\pycqBot\socketApp.py", line 269, in main_logic
    self._on_message(await websocket.recv())
  File "E:\conda\envs\qqbot\lib\site-packages\pycqBot\cqApi.py", line 542, in _on_message
    message, event_name = super()._on_message(message)
  File "E:\conda\envs\qqbot\lib\site-packages\pycqBot\socketApp.py", line 316, in _on_message
    self.__event[event_name](message_data)
  File "E:\conda\envs\qqbot\lib\site-packages\pycqBot\cqApi.py", line 975, in message_group_normal
    self._message_group(message)
  File "E:\conda\envs\qqbot\lib\site-packages\pycqBot\cqApi.py", line 908, in _message_group
    self.on_group_msg(message)
  File "C:\Users\admin\Desktop\1\qqbot.py", line 321, in on_group_msg
    reply_msg(message, at_flag)
  File "C:\Users\admin\Desktop\1\qqbot.py", line 206, in reply_msg
    send_sticker(message)
  File "C:\Users\admin\Desktop\1\qqbot.py", line 173, in send_sticker
    with open('sticker.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sticker.json'
[2023-05-11 20:12:13,215][cqhttp_shell/WARNING] PyCqBot: go-cqhttp 警告 ocr image error: server error, code: 100 msg: hit failed,need upload
[2023-05-11 20:12:13,215][asyncHttp_loop/ERROR] PyCqBot: api 发生错误 OCR_API_ERROR: server error, code: 100 msg: hit failed,need upload code: 100
识别文字: 无文字  识别用时: 0.391s



这是在输入了5次后出现的报错。这个文件在哪里

**Comment by mlpxt** [comment]
上面的文件已经找到了。

请问一下他只回答表情包是什么情况，一直没有说话
![图片](https://github.com/LUMOXu/Spit_chatBot/assets/108312263/1f37b8bc-4be6-4a5f-aa3e-0dcf256337e3)
![图片](https://github.com/LUMOXu/Spit_chatBot/assets/108312263/29863386-13b8-4eb1-bf2d-15e111938975)

是网络问题吗

**Comment by LUMOXu** [comment]
是网络问题

**Comment by mlpxt** [comment]
好吧，那我这边没什么问题了，感谢您的解答

**Comment by LUMOXu** [comment]
等等，还有一种可能，如果你这个Internet issues这行是瞬间出现的话，可能是parse_reply出错了，都怪我try设的范围太大

**Comment by LUMOXu** [comment]
不过这种情况我没遇到，如果你编辑了parse reply函数，可能会出这个问题

**Comment by mlpxt** [comment]
阿这，我这边的确是瞬间出现的。你所说的函数我没有进行编辑过

**Comment by FanhuaAwA** [comment]
> 

同样我我也发生了你这个报错，请问是如何修复的

**Comment by mlpxt** [comment]
还没有修复，需要看大佬的操作了

**Comment by LUMOXu** [comment]
那你把qqbot里reply_msg的
```
    try:
        replies = chat.parse_reply(chat.answer(temp_chat_record, prompt))  # may stuck at this step.
        if replies and reply_flag:
            replies[0] = sender + ', ' + replies[0]
    except:
        print('Internet issues! Will not answer this time.')
        if random.random() < STICKER_PROB:
            send_sticker(message)
        return
```
改成
```
replies = chat.parse_reply(chat.answer(temp_chat_record, prompt))  # may stuck at this step.
        if replies and reply_flag:
            replies[0] = sender + ', ' + replies[0]
```
也就是把try...except删了，看看报错是什么

**Comment by FanhuaAwA** [comment]
> 那你把qqbot里reply_msg的
> 
> ```
>     try:
>         replies = chat.parse_reply(chat.answer(temp_chat_record, prompt))  # may stuck at this step.
>         if replies and reply_flag:
>             replies[0] = sender + ', ' + replies[0]
>     except:
>         print('Internet issues! Will not answer this time.')
>         if random.random() < STICKER_PROB:
>             send_sticker(message)
>         return
> ```
> 
> 改成
> 
> ```
> replies = chat.parse_reply(chat.answer(temp_chat_record, prompt))  # may stuck at this step.
>         if replies and reply_flag:
>             replies[0] = sender + ', ' + replies[0]
> ```
> 
> 也就是把试试...except删了，看看报错是什么

我这边消息达到五条，机器人会报错和他上面那个一样 奇怪了

**Comment by mlpxt** [comment]
不行了，搞不动了。[FanhuaAwA](https://github.com/FanhuaAwA)。你和大佬进行交流吧

**Comment by LUMOXu** [comment]
报错是什么，我需要这个来debug

**Comment by FanhuaAwA** [comment]
> 报错是什么，我需要这个来调试

前面那个问题我重启了之后就好了，但机器人经常会回复个6或者？ 而且哥咱能把这个感觉被怀疑就把自己关了的功能给弱化一下吗有点影响体验。

**Comment by LUMOXu** [comment]
其实spit在潜伏的过程中全程没用过那个功能，感觉整活意义更大

**Comment by darkgreensky** [comment]
有时候回复的时候会有个“你：”，这怎么处理呀

**Comment by LUMOXu** [comment]
> 有时候回复的时候会有个“你：”，这怎么处理呀

请仔细看看别的issues。
